Controllers/CardController.cs
using CardValidator.Dto;
using CardValidator.Interfaces;
using CardValidator.Models;
using CardValidator.Services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CardValidator.Controllers
{
    public class CardController : Controller
    {
        private readonly ICardService _cardService;
        private readonly ICardValiditorService _cardValiditorService;
        private readonly ICardProviderService _cardProviderService;
        private readonly IHttpContextAccessor _httpContext;
        private readonly List<Services.Validator> _validators;

        public CardController(ICardService cardService,
                              ICardValiditorService cardValiditorService,
                              ICardProviderService cardProviderService,
                              IHttpContextAccessor httpContext)
        {
            _cardService = cardService;
            _cardValiditorService = cardValiditorService;
            _cardProviderService = cardProviderService;
            _httpContext = httpContext;
            _validators = new List<Services.Validator>();
        }

        public async Task<IActionResult> Index()
        {
            return View(await _cardService.GetCards());
        }

        public async Task<IActionResult> SaveCard(string cardNumber)
        {
            if (!Validate(cardNumber))
                return View("Index", await _cardService.GetCards()); 

            var cardProvider = await _cardProviderService.GetCardProvider(_cardValiditorService.GetCardProvider(cardNumber));

            await _cardService.SaveCard(new CardDTO
            {
                CardProviderId = cardProvider.CardProviderId,
                CardNumber = cardNumber,
            });

            return View("Index", await _cardService.GetCards());
        }

        public async Task<IActionResult> DeleteCard(int id)
        {
            await _cardService.DeleteCard(id);

            return View("Index", await _cardService.GetCards());
        }

        public bool Validate(string cardNumber)
        {
            _validators.Add(new CardNumberValidate(_cardValiditorService, cardNumber, _httpContext.HttpContext));
            _validators.Add(new ExistsValidate(_cardService, cardNumber, _httpContext.HttpContext));
            _validators.Add(new ProviderConfiguredValidate(_cardValiditorService, cardNumber, _httpContext.HttpContext));

            CardValidate cardValidator = new CardValidate(_validators);

            return cardValidator.Validate();
        }
    }
}

Controllers/CardProviderController.cs
using CardValidator.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CardValidator.Controllers
{
    public class CardProviderController : Controller
    {
        private readonly ICardProviderService _cardProviderService;

        public CardProviderController(ICardProviderService cardProviderService)
        {
            _cardProviderService = cardProviderService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _cardProviderService.GetCardProviders());
        }

        public async Task<IActionResult> EnableProvider(int id ,bool enable)
        {
            await _cardProviderService.SetCardProviderConfiguration(id, enable);

            return View("Index", await _cardProviderService.GetCardProviders());
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="https://d1s4umho1unrgr.cloudfront.net/2021/12/14/11/35/06/f1bc82e1-51d8-4b84-82fa-f1180d62cb19/DZqQ9ehcRZCNPnWONk4o?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMXM0dW1obzF1bnJnci5jbG91ZGZyb250Lm5ldC8yMDIxLzEyLzE0LzExLzM1LzA2L2YxYmM4MmUxLTUxZDgtNGI4NC04MmZhLWYxMTgwZDYyY2IxOS9EWnFROWVoY1JaQ05QbldPTms0byIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY4NzMzMDgyNn19fV19&Signature=k80oNlkgPC20f-Fh3-HhrDNSpsuiEj1v3W~82Qmu-BiRYSP3nBvjpwzqRDzery5DCssSKOT06G9s1hvcOlIfVRvcDnwIPrQWQFvuI9ILuxQUosq0vowqZXj~QgMFPniJvl7UC-qpiR9IaoJWnRw19WRQaQUF3BMYV6VAPhJ4~lS5S4V5zHj6qLw~MbWf5YErOgvo2LJu1brdJfzRk3GdRef0tA4q3f1px~77IxwKAYk03u2IqPQwdCCPDExhaChW4odOuVxseg6I-UiSxs4lBhnUMxAZBdNK27FSkvjkcQRXr3GXHspUYLDtvZ15IWBMtyqldUghAq-nSv2nyIiQ5g__&Key-Pair-Id=APKAITFCDZDSWOJU5OZA">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CardValidator.styles.css" asp-append-version="true" />
    <link href="~/css/datatables.min.css" rel="stylesheet" />
    <link href="~/css/jquery.toast.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Card" asp-action="Index">Cards</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CardProvider" asp-action="Index">Card Providers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CardValidator - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/23784d82e7.js" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery.toast.min.js"></script>
    <script src="~/js/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>